Algoritmo "concatenação"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison
// Descrição   : concatenação
// Autor(a)    : Murilo
// Data atual  : 22/10/2025
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome: ")
   leia(nome)
   escreval("Digite o seu número")
   leia(numero)
   
   escreval(nome , " : " , numero, 15)

Fimalgoritmo