Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Meu primeiro algoritmo para ler nota
// Autor(a)    : Murilo
// Data atual  : 23/09/2025
Var
// Seção de Declarações das variáveis 
      nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      nota <- 100
      escreva("Resultado ", nota)

Fimalgoritmo